language: bash

services: docker


script:
  - docker build -t $REGISTRY/blackeeper/postgres:10.7-with-postgis .
  # - docker run --name postgis -it -d $REGISTRY/blackeeper/postgres:10.7-with-postgis
  # - docker ps -a
  # - sleep 10
  # - docker exec -it postgis /postgis_test.sh 
  # - docker rm -f postgis
  - docker info
  - echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin $REGISTRY
  - docker push $REGISTRY/blackeeper/postgres:10.7-with-postgis
